def elastest_url = ''
node('et_in_et'){
    elastest(tss: ['EUS'], surefireReportsPattern: '**/target/surefire-reports/TEST-*.xml', project: 'ETinET', sut: 11) {        
        stage ('docker container')
            def mycontainer = docker.image('elastest/ci-docker-e2e:latest')
            mycontainer.pull()
            mycontainer.inside()  {
                sh 'env | sort'
                stage ('prepare test')
                    git 'https://github.com/elastest/elastest-bigdata-service.git'
                    elastest_url = env.ET_SUT_PROTOCOL + '://' + env.ET_SUT_HOST + ':' + env.ET_SUT_PORT
                    
                stage ("Run tests")
                    try {
                        sh "cd e2e-test;sudo pip install requests;python e2etest.py ${elastest_url}"
                    } catch(e) {
                        echo 'Err: ' + e.toString()
                    } finally {
                        step([$class: 'JUnitResultArchiver', testDataPublishers: [[$class: 'AttachmentPublisher']], testResults: '**/target/surefire-reports/TEST-*.xml'])
                    }
            }
    }
}
