def elastest_url = ''
node('et_in_et'){
    elastest(tss: ['EUS'], surefireReportsPattern: '**/target/surefire-reports/TEST-*.xml', project: 'ETinET', sut: 11) {        
        stage ('docker container')
            def mycontainer = docker.image('elastest/ci-docker-compose-py-siblings:latest')
            mycontainer.pull()
            mycontainer.inside()  {
                
                stage ('prepare test')
                    git 'https://github.com/elastest/elastest-bigdata-service.git'
                    elastest_url = env.ET_SUT_PROTOCOL + '://' + env.ET_SUT_HOST + ':' + env.ET_SUT_PORT
                sh "env | sort"    
                stage ("Run tests")
                    try {
                        sh "cd e2e-test;python e2etest.py ${elastest_url}"
                    } catch(e) {
                        echo 'Err: ' + e.toString()
                    } 
            }
    }
}
